name: for_the_table
description: "A new Flutter project."
publish_to: "none"
# version: 0.1.0
version: "1.0.1+1.0"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  awesome_notifications: ^0.8.2
  cached_network_image: ^3.3.1
  camera: ^0.10.0+4
  chips_choice: ^3.0.1
  crypto: ^3.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  flutter_facebook_auth: ^7.0.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  glassmorphism: ^3.0.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  http: ^1.2.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.9.0
  label_marker: ^1.0.1
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  share_plus: ^10.0.2
  sign_in_with_apple: ^6.1.2
  swipe_cards: ^1.0.0
  uuid: ^3.0.4
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  after_layout: ^1.2.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  #* Code Generation
  build_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-full.jpeg"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/temp/
