name: for_the_table
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^8.1.3
  flutter_riverpod: ^2.3.7
  loading_animation_widget: ^1.2.0+4
  flutter_screenutil: ^5.9.0
  dio: ^5.3.2
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.4
  intl: ^0.18.1
  image_picker: ^1.0.4
  pinput: ^4.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  hive: ^2.2.3
  path_provider: ^2.1.1  
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  chips_choice: ^3.0.1
  flutter_card_swiper: ^7.0.1
  google_maps_flutter: ^2.2.8
  label_marker: ^1.0.1
  swipe_cards: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  #* Code Generation
  build_runner: 
  auto_route_generator: ^8.0.0
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-full.jpeg"
  remove_alpha_ios: true
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/temp/

